trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: BUILD
  jobs:
  - template: adf-build-job.yml
    parameters:
      subscriptionId: 67fa9cc2-5f9a-4d41-bc80-02dfe6c03ff6
      resourceGroupName: DEV_RG
      dataFactoryName: RebrickableAdfDev
      repoRootFolder: /data-factory/
      packageJsonFolder: /devops/

- stage: DEV
  variables:
  - group: Dev
  jobs:
  - template: adf-deploy-job.yml
    parameters:
      environmentName: DEV
      subscriptionId: 67fa9cc2-5f9a-4d41-bc80-02dfe6c03ff6
      resourceGroupName: DEV_RG
      dataFactoryName: RebrickableAdfDev
      serviceConnectionName: cicd dev
      overrideParameters: >
        -AzureDatabricks_http_downloads_ls_properties_typeProperties_existingClusterId $(AzureDatabricks_http_downloads_ls_properties_typeProperties_existingClusterId)
        -AzureDataLakeStorage_ls_properties_typeProperties_url $(AzureDataLakeStorage_ls_properties_typeProperties_url)
        -AzureKeyVault_ls_properties_typeProperties_baseUrl $(AzureKeyVault_ls_properties_typeProperties_baseUrl)
        -HttpServer_ls_properties_typeProperties_url $(HttpServer_ls_properties_typeProperties_url)
        -HttpServer_ls_properties_typeProperties_userName $(HttpServer_ls_properties_typeProperties_userName)
        -RestService_ls_properties_typeProperties_url $(RestService_ls_properties_typeProperties_url)